name: Deploy and Health Check

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: cruddistribuida
          heroku_email: clobodiaz@outlook.com

  health-check:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Validate Health
        run: |
          status_code=$(curl -s -o /dev/null -w "%{http_code}" https://cruddistribuida.herokuapp.com/health)
          if [ $status_code -eq 200 ]; then
            echo "Health check passed"
          else
            echo "Health check failed. Status code: $status_code"
            exit 1
          fi
